version: '3.7'

services:

  app:
    build: .
    ports: 
      - "3001:3000"
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      REACT_APP_SERVER_URL: http://localhost:3000
