version: '3.7'

services:
  postgres:
    image: postgres:11.2-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env-prod-back

  api:
    image: docker.pkg.github.com/helloworld-repo/helloworld-api/server:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - .env-prod-back
    command: npm start

  app:
    build: .
    env_file:
      - .env-prod-front
    depends_on:
      - api
    command: npm run build

  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
      - app
