version: '3.7'

services:

  app:
    build: .
    command: npm start
    ports: 
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules

    environment:
      CHOKIDAR_USEPOLLING: "true"
