version: '3.7'

services:
  app:
    image: docker.pkg.github.com/helloworld-repo/helloworld-web/app:latest
    ports:
      - "3001:3000"
    env_file:
      - .env-prod-front
    depends_on:
      - api
    command: npm start

  api:
    image: docker.pkg.github.com/helloworld-repo/helloworld-api/server:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - .env-prod-back
    command: npm start

  postgres:
    image: postgres:11.2-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env-prod-back
